version: "2"
services:
  web:
    image: micro-nginx
    links:
      - upload
      - preview
      - save
    ports:
      - "8000:80"
  upload:
    image: micro-upload
    environment:
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_SECRET_KEY=${AWS_SECRET_KEY}
  preview:
    image: micro-preview
    environment:
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_SECRET_KEY=${AWS_SECRET_KEY}
  save:
    image: micro-save
    environment:
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_SECRET_KEY=${AWS_SECRET_KEY}
